### ISSUE TITLE
editspam warnings

### ISSUE THREAD

**Issue by amstan** [amstan/hyperserv#11]
implement an edit event, and add an eventHandler which coults them and notices on too many.

**Comment by Windecker** [comment]
Improved functionality could be brought by having a system that detects a decent selection size but only reports it if the grid size is small enough.
A larger yet selection would be reported on all grid sizes.

**Comment by amstan** [comment]
maybe deny editing actions if it's large scale spamming(raising the whole map with the smallest grid size), or maybe even autokick for such a thing for people that are under trusted

**Comment by Windecker** [comment]
That is very good idea. 
Denying actions for the vast editspam would be idea.
The kicking would need to be set carefully though.

**Comment by amstan** [comment]
Meh.. anyone really wanting this? Downsides is that it would require time and it might slowdown the server while parsing edit packets.
