### ISSUE TITLE
Invisible login

### ISSUE THREAD

**Issue by Windecker** [amstan/hyperserv#15]
Implement a way to login when ingame without the server relaying the (X-User has logged in as X-Name)
ex #loginsilent

**Comment by Windecker** [comment]
[ 21:48:19 ] <amstan> i can make a #login user password silent
[ 21:48:20 ] <[Jake]> #loginsilent doesnt allow the server to relay login messages
[ 21:48:21 ] -hyperserv_test- CSError: No such command "loginsilent"
[ 21:48:23 ] <[Jake]> alright
[ 21:48:40 ] <[Jake]> its so you can join a server, login quietly, and watch. :]
[ 21:48:43 ] <amstan> put this as a comment in that issue

**Comment by amstan** [comment]
do we need this?

**Comment by Calinou** [comment]
+1 for the loginsilent...
eg : there's a mass kicker. You login. He sees it. He disconnects before, you could not catch his IP to ban him.

**Comment by amstan** [comment]
There are much better ways to deal with them.
1.Their ip is in the log anyway.
2.IPs are useless the next day
3.Ban by name, this way the alias tracking framework can deal with it(upcoming)

**Comment by Calinou** [comment]
If the guy change his name then ?
