### ISSUE TITLE
Cant make??!!!

### ISSUE THREAD

**Issue by fetzjr** [amstan/hyperserv#41]
Here is what i get in error:

hyperserv@debian:~/hyperserv$ make
[ 17%] Built target sauertools
[ 64%] Built target enet
make[2]: **\* No rule to make target `/usr/libpython2.6.so', needed by`src/hyperserv'.  Stop.
make[1]: **\* [src/CMakeFiles/hyperserv.dir/all] Error 2
make: **\* [all] Error 2
hyperserv@debian:~/hyperserv$

**Comment by amstan** [comment]
You don't seem to have all the python deps installed.

**Comment by fetzjr** [comment]
What else could i add?

**Comment by fetzjr** [comment]
I have suckerserv compiled... (im on debian) I think it has to do with python (as you said)
