### ISSUE TITLE
Can't start server D:

### ISSUE THREAD

**Issue by fetzjr** [amstan/hyperserv#42]
hyperserv@debian:~/hyperserv$ ./start_server.py
Traceback (most recent call last):
  File "/home/hyper/hyperserv/src/pyscripts/hyperserv/events.py", line 1, in <module>
    import timers
  File "/home/hyper/hyperserv/src/pyscripts/hyperserv/timers.py", line 1, in <module>
    from twisted.internet.task import LoopingCall
ImportError: No module named twisted.internet.task
Error initializing python modules.
Server initialization failed.
Python Error: Invalid handler to triggerEvent function.
hyperserv@debian:~/hyperserv$ 

How do i fix this?

**Comment by amstan** [comment]
Do you have twisted installed?

**Comment by fetzjr** [comment]
umm nope. I have twistd though...

**Comment by amstan** [comment]
Ok dude:
1. You have to read the README, exactly what it says. You can't expect it to work when you install similar named libraries.
2. This issue tracker is not about you trying to make it going. These are not issues related to the software, these are problems with your attitude.
3. I'm on vacation, I barely have internet, yet you're spamming this issue tracker(including my email) like it's the most used software on earth. Expect 48 hours for any reply.
4. Calling my software names is definitely not going to make me help you.
5. I really don't think you're in the right mindset for trying this mod, you have to be open to learning how it works and all the intricacies of it. I mostly made it for myself and my friends, the few servers running it are admined by me. I suggest running some other mod instead that's "easier" to use.
