### ISSUE TITLE
Null map on first connect

### ISSUE THREAD

**Issue by Windecker** [amstan/hyperserv#5]
Thar be no map upon first connect. The server denies a map change to he who is not master, and therefor leaves the client with no map loaded and a pleasant view of the main menu. 

Need an auto map load script for server startup, and then the server can do as all others do. Remember the previous map it was on.

**Comment by amstan** [comment]
see http://github.com/SirAlex/hyperserv/issues#issue/4

**Comment by amstan** [comment]
see:
cfg defaultmap mhstreet
cfg defaultmode coop
cfg defaultmastermode open
